name: CI - production

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: yarn install, build
        run: |
          yarn
          yarn build --if-present
        env:
          REACT_APP_API_URL: https://api.piction.network/
          REACT_APP_TAGMANAGER_CONTAINER_ID: GTM-KCZDV3M
      - name: Deploy to S3
        uses: actions/aws/cli@master
        with:
          args: "s3 sync build s3://production.piction.network"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
